<?php
/**
 * Implements hook_js_settings_alter().
 * - add "ago_access_token" to the drupalSettings
 */
function agocms_js_settings_alter(array &$settings,
            \Drupal\Core\Asset\AttachedAssetsInterface $assets) {
  // get current session to find access token
  $request = \Drupal::request();
  $session = $request->getSession();

  // add frontend references
  $settings['agocms_token'] = $session->get('ago_access_token');
}

/**
 * Implements hook_page_attachments()
 * - add core ago and agocms JS to every page
 */
function agocms_page_attachments(array &$page) {
  $page['#attached']['library'][] = 'agocms/agocms';
}

/**
 * Implements hook_theme().
 */
function agocms_theme($existing, $type, $theme, $path) {
  return [
    'view_config_form' => []
  ];
}

// add Drupal modals to view config page
function agocms_preprocess_node__page(array &$variables) : void {
  $variables['#attached']['library'][] = 'agocms/view-conf';
}
